### ISSUE TITLE
Would be really nice if this gem would have some kind of documentation

### ISSUE THREAD

**Issue by bogdanRada** [Genshin/phantom_svg#17]
I really find this gem very interesting , but there is no documentation . I would really appreciate if this could be documented a bit at least with some basic steps.

**Comment by Kagetsuki** [comment]
We originally intended to build this out and add documentation, but there was a total lack of interest so we're more or less just using it for internal use. It's only real use is converting between a semi-proprietary frame animated SVG and Animated PNG, but it can re-size and export between these formats. As for features, resizing is at a fixed rate and is canvas-only. We're planning on adding cropping in the future, but have no concrete estimate on implementation.

If you're looking to convert/compile frame animated SVG's and/or convert to/from Animated PNG I can see about writing a little sample - but if you actually want a full manipulation library I'm afraid you won't find this to be what you're looking for.

Also I'm fairly certain this doesn't work on Windows at all and it takes an install of apngasm 3 with HomeBrew or from source to work on OS X. If you're looking at putting this in some sort of tool or client library I have a feeling it could be a big headache to deal with distribution.

**Comment by bogdanRada** [comment]
i am actually very interested in converting between SVG and PNG ( mostly just from SVG to PNG only). And i only use Linux, don't really like Windows or OSX for development. 

I would really appreciate that small sample application. Thank you very much,.

**Comment by Kagetsuki** [comment]
No problem then!

```ruby
require 'phantom/svg'

sv = Phantom::SVG::Base.new('./my-svg.svg') # create an SVG base container
sv.width = 200 # this is in pixels
sv.height = 200 # this is in pixels
sv.save_apng('./my-apng.png') # note it's apng, not png - but a single frame will just be a normal png anyway
```

**Comment by bogdanRada** [comment]
thanks

**Comment by Kagetsuki** [comment]
No problem - if you have any other questions I'll do my best to help you out, feel free to just re-open this issue.
